import {EMPTY_DOC,cloneDoc,normSel,selectedOrAll,replaceRange,typingUpdate,addMark,clearMarks,setAlign,alignAt,applyList,plainText,segments,unicodeStyle,combine,caseTransform} from './core.js';
import {EMOJI_CATEGORIES} from './emoji-data.js';
import {LANGS,T} from './i18n.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lang=localStorage.getItem('textaura-lang')||((navigator.language||'fr').slice(0,2));if(!LANGS.includes(lang))lang='fr';
let doc=loadDoc(), selection={start:0,end:0}, remembered=null, undo=[], redo=[], activeEmoji='smileys';
const editor=$('#editor'),preview=$('#preview'),count=$('#count'),toast=$('#toast'),colorDialog=$('#color-dialog'),emojiDialog=$('#emoji-dialog');
function tr(k){return T[lang]?.[k]??T.fr[k]??k}
function loadDoc(){try{const x=JSON.parse(localStorage.getItem('textaura-doc')||'null');return x&&typeof x.text==='string'&&Array.isArray(x.marks)&&Array.isArray(x.paragraphs)?x:cloneDoc(EMPTY_DOC)}catch{return cloneDoc(EMPTY_DOC)}}
function save(){localStorage.setItem('textaura-doc',JSON.stringify(doc));localStorage.setItem('textaura-lang',lang)}
function notice(s){toast.textContent=s;toast.hidden=false;clearTimeout(notice.t);notice.t=setTimeout(()=>toast.hidden=true,1800)}
function push(){undo.push({doc:cloneDoc(doc),selection:{...selection}});if(undo.length>100)undo.shift();redo=[]}
function restore(x){doc=cloneDoc(x.doc);selection={...x.selection};render();setTimeout(()=>{editor.focus({preventScroll:true});editor.setSelectionRange(selection.start,selection.end)},0)}
function doUndo(){if(!undo.length)return;redo.push({doc:cloneDoc(doc),selection:{...selection}});restore(undo.pop())}
function doRedo(){if(!redo.length)return;undo.push({doc:cloneDoc(doc),selection:{...selection}});restore(redo.pop())}
function currentSel(all=true){const s=normSel(remembered??selection,doc.text.length);return all&&s.start===s.end?{start:0,end:doc.text.length}:s}
function remember(){const a=editor.selectionStart??0,b=editor.selectionEnd??a;selection=normSel({start:a,end:b},doc.text.length);if(selection.start!==selection.end)remembered={...selection}}
function replaceSelected(value,all=true){if(!doc.text&&all){notice(tr('empty'));return}push();const r=currentSel(all),x=replaceRange(doc,r,value);doc=x.doc;selection=x.selection;remembered={...selection};render();focusSelection()}
function focusSelection(){setTimeout(()=>{editor.focus({preventScroll:true});editor.setSelectionRange(selection.start,selection.end)},0)}
function applyUnicode(style){const r=currentSel();replaceSelected(unicodeStyle(doc.text.slice(r.start,r.end),style))}
function applyDecoration(op){const r=currentSel();if(op==='underline'){push();doc=addMark(doc,r,{underline:true});render();return}if(op==='highlight'){openColors('background');return}const v=doc.text.slice(r.start,r.end);replaceSelected(op==='strike'?combine(v,'\u0336'):op==='over'?combine(v,'\u0305'):op==='spark'?`✨ ${v} ✨`:op==='heart'?`💖 ${v} 💖`:`【${v}】`)}
function applyCase(op){const r=currentSel();replaceSelected(caseTransform(doc.text.slice(r.start,r.end),op,lang))}
function applyAlignment(a){if(!doc.text){notice(tr('empty'));return}push();doc=setAlign(doc,currentSel(),a);render()}
function list(op){if(!doc.text){notice(tr('empty'));return}push();const x=applyList(doc,currentSel(),op);doc=x.doc;selection=x.selection;remembered={...selection};render();focusSelection()}
function addColor(kind,color){push();const r=currentSel();doc=addMark(doc,r,kind==='color'?{color}:kind==='background'?{background:color}:{underlineColor:color});render()}
function removeColors(){push();doc=clearMarks(doc,currentSel());render()}
function renderPreview(){preview.replaceChildren();if(!doc.text){preview.textContent='…';preview.classList.add('empty');return}preview.classList.remove('empty');let start=0;const lines=doc.text.split('\n');lines.forEach(line=>{const p=document.createElement('div');p.className='preview-line';p.style.textAlign=alignAt(doc,start);if(alignAt(doc,start)==='justify')p.style.textAlign='justify';const end=start+line.length;segments(doc,start,end).forEach(seg=>{const span=document.createElement('span');span.textContent=seg.text;Object.assign(span.style,seg.style);p.append(span)});if(!line)p.append(document.createElement('br'));preview.append(p);start=end+1})}
function render(){editor.value=doc.text;count.textContent=`${[...doc.text].length} ${tr('chars')}`;renderPreview();save();$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length}
function setLanguage(v){lang=v;document.documentElement.lang=v;document.documentElement.dir=v==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));$$('.tool[data-key]').forEach(b=>{const label=b.querySelector('span');if(label)label.textContent=tr(b.dataset.key)});editor.placeholder=tr('hint');$('#emoji-search').placeholder=tr('search');$('#language').value=v;renderEmojiTabs();renderEmoji();render();save()}
function makeTools(){const style=[['Abc','normal'],['𝗔𝗯𝗰','bold'],['𝘈𝘣𝘤','italic'],['𝘼𝙗𝙘','boldItalic'],['𝐀𝐛𝐜','serif'],['𝙰𝚋𝚌','mono'],['𝔸𝕓𝕔','double'],['𝒜𝒷𝒸','script'],['ᴀʙᴄ','small'],['Ａｂｃ','full'],['Ⓐⓑⓒ','circle']];toolRow('#style-tools',style,k=>applyUnicode(k));toolRow('#decor-tools',[['A̲bc','underline'],['A̶bc','strike'],['A̅bc','over'],['▰ Abc','highlight'],['✨ Abc','spark'],['💖 Abc','heart'],['【Abc】','frame']],applyDecoration);toolRow('#case-tools',[['Abc.','sentence'],['abc','lower'],['ABC','upper'],['Abc Def','title'],['aBC','toggle'],['AbCd','sponge'],['a_b','snake'],['a-b','kebab'],['aBc','camel'],['ABc','pascal'],['é→e','noAccents'],['a b→ab','noSpaces']],applyCase);toolRow('#align-tools',[['↤','left'],['↔','center'],['↦','right'],['☷','justify']],applyAlignment);toolRow('#list-tools',[['1.','number'],['A.','letter'],['I.','roman'],['•','bullet'],['–','dash'],['✓','check'],['➜','arrow'],['★','star'],['◆','diamond'],['✕','remove']],list)}
function toolRow(sel,items,fn){const row=$(sel);items.forEach(([sample,key])=>{const b=document.createElement('button'),strong=document.createElement('strong'),label=document.createElement('span');b.type='button';b.className='tool';strong.textContent=sample;label.textContent=tr(key);b.append(strong,label);b.dataset.key=key;b.addEventListener('pointerdown',e=>e.preventDefault());b.addEventListener('click',()=>fn(key));row.append(b)})}
function openColors(kind){if(!doc.text){notice(tr('empty'));return}remember();colorDialog.dataset.kind=kind;colorDialog.showModal()}
function buildColors(){const colors=['#111827','#6b7280','#dc2626','#f97316','#eab308','#16a34a','#14b8a6','#0284c7','#2563eb','#7c3aed','#c026d3','#db2777','#7c2d12','#0f766e','#4338ca','#be123c','#000000','#ffffff'];const grid=$('#color-grid');colors.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=c;b.ariaLabel=c;b.addEventListener('click',()=>{addColor(colorDialog.dataset.kind,c);colorDialog.close()});grid.append(b)})}
function renderEmojiTabs(){const tabs=$('#emoji-tabs');tabs.replaceChildren();EMOJI_CATEGORIES.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='emoji-tab'+(activeEmoji===c.id?' active':'');b.textContent=`${c.icon} ${c.name[lang]??c.name.fr}`;b.onclick=()=>{activeEmoji=c.id;renderEmojiTabs();renderEmoji()};tabs.append(b)})}
function renderEmoji(){const cat=EMOJI_CATEGORIES.find(c=>c.id===activeEmoji)??EMOJI_CATEGORIES[0],q=$('#emoji-search').value.trim();$('#emoji-category').textContent=cat.name[lang]??cat.name.fr;const grid=$('#emoji-grid');grid.replaceChildren();cat.items.filter(e=>!q||e.includes(q)).forEach(e=>{const b=document.createElement('button');b.type='button';b.className='emoji-cell'+(doc.text.includes(e)?' used':'');b.textContent=e;b.ariaLabel=e;b.onclick=()=>{const s=currentSel(false);push();const x=replaceRange(doc,s,e);doc=x.doc;selection={start:x.selection.end,end:x.selection.end};remembered=null;render();renderEmoji()};grid.append(b)})}
async function writeClipboard(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return true}}catch{}const area=document.createElement('textarea');area.value=text;area.readOnly=true;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();return ok}
async function copy(){if(!doc.text){notice(tr('empty'));return}if(await writeClipboard(plainText(doc)))notice(tr('copied'))}
async function share(){if(!doc.text){notice(tr('empty'));return}const text=plainText(doc);if(navigator.share)try{await navigator.share({text,title:'TextAura'});return}catch(e){if(e.name==='AbortError')return}if(await writeClipboard(text))notice(tr('copied'))}
async function exportPng(){
 if(!doc.text){notice(tr('empty'));return}
 const width=1080,pad=72,scale=Math.min(3,window.devicePixelRatio||2);
 const card=document.createElement('div');
 Object.assign(card.style,{boxSizing:'border-box',width:`${width}px`,padding:`${pad}px`,background:'#ffffff',color:'#1b1f3b',fontFamily:'system-ui, sans-serif'});
 const brand=document.createElement('div');brand.textContent='TextAura ✦';Object.assign(brand.style,{color:'#7c3aed',fontSize:'34px',fontWeight:'800',marginBottom:'34px'});card.append(brand);
 const content=preview.cloneNode(true);content.removeAttribute('id');content.className='';Object.assign(content.style,{fontSize:'38px',lineHeight:'1.5',whiteSpace:'pre-wrap',overflowWrap:'anywhere',background:'#fff',padding:'0',border:'0'});
 [...content.children].forEach(line=>Object.assign(line.style,{display:'block',minHeight:'1.5em'}));card.append(content);
 Object.assign(card.style,{position:'fixed',left:'-20000px',top:'0'});document.body.append(card);const height=Math.max(420,Math.ceil(card.scrollHeight));card.remove();
 const clone=card.cloneNode(true);clone.style.position='static';clone.style.left='auto';clone.setAttribute('xmlns','http://www.w3.org/1999/xhtml');
 const serialized=new XMLSerializer().serializeToString(clone);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><foreignObject width="100%" height="100%">${serialized}</foreignObject></svg>`;
 const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();
 try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url});const canvas=document.createElement('canvas');canvas.width=width*scale;canvas.height=height*scale;const ctx=canvas.getContext('2d');ctx.scale(scale,scale);ctx.drawImage(img,0,0,width,height);await new Promise(resolve=>canvas.toBlob(file=>{if(file){const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download='TextAura-publication.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}resolve()},'image/png',1))}finally{URL.revokeObjectURL(url)}
}
function init(){makeTools();buildColors();setLanguage(lang);editor.addEventListener('select',remember);editor.addEventListener('keyup',remember);editor.addEventListener('pointerup',remember);editor.addEventListener('input',()=>{push();doc=typingUpdate(doc,editor.value);selection={start:editor.selectionStart,end:editor.selectionEnd};remembered=null;render();editor.setSelectionRange(selection.start,selection.end)});$$('button').forEach(b=>{if(!b.closest('dialog'))b.addEventListener('pointerdown',e=>{if(b.id!=='editor')e.preventDefault()})});$('#language').onchange=e=>setLanguage(e.target.value);$('#undo').onclick=doUndo;$('#redo').onclick=doRedo;$('#clear').onclick=()=>{if(!doc.text)return;push();doc=cloneDoc(EMPTY_DOC);selection={start:0,end:0};remembered=null;render()};$('#hide-keyboard').onclick=()=>{remember();editor.blur();notice(tr('saved'))};$('#emoji-open').onclick=()=>{remember();renderEmojiTabs();renderEmoji();emojiDialog.showModal()};$('#emoji-search').oninput=renderEmoji;$('#copy').onclick=copy;$('#share').onclick=share;$('#png').onclick=exportPng;$('#text-color').onclick=()=>openColors('color');$('#highlight-color').onclick=()=>openColors('background');$('#underline-color').onclick=()=>openColors('underline');$('#remove-colors').onclick=removeColors;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());window.addEventListener('beforeunload',save);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render()}
init();
