import {EMPTY_DOC,cloneDoc,normSel,selectedOrAll,replaceRange,typingUpdate,addMark,clearMarks,setAlign,alignAt,applyList,plainText,segments,unicodeStyle,combine,caseTransform} from './core.js';
import {EMOJI_CATEGORIES} from './emoji-data.js';

const LANGS=['fr','en','es','de','ar'];
const T={
 fr:{tag:'Donnez du style à vos publications ✨',your:'Votre texte',hint:'Écrivez ou collez votre publication ici…',tip:'Sélectionnez un passage, puis touchez un outil. Sans sélection, l’action s’applique à tout le texte.',chars:'caractères',undo:'Annuler',redo:'Rétablir',emoji:'Emojis',clear:'Effacer',styles:'Styles rapides',decor:'Décorations',formats:'Casse et formats',colors:'Couleurs et surlignage',paragraphs:'Alignement, paragraphes et listes',preview:'Aperçu',copy:'Copier',share:'Partager',png:'Exporter PNG',privacy:'🔒 Hors ligne, sans compte et sans traçage. Vos textes restent sur cet appareil.',search:'Rechercher un emoji…',close:'Fermer',choose:'Choisir une couleur',empty:'Écrivez d’abord un texte.',copied:'Texte copié',saved:'Brouillon sauvegardé localement',normal:'Normal',bold:'Gras',italic:'Italique',boldItalic:'Gras italique',serif:'Gras serif',mono:'Monospace',double:'Double trait',script:'Cursif',small:'Petites capitales',full:'Pleine largeur',circle:'Cerclé',underline:'Souligné',strike:'Barré',over:'Ligne supérieure',highlight:'Surligneur',spark:'Étincelles',heart:'Cœurs',frame:'Encadré',sentence:'Phrase',lower:'minuscules',upper:'MAJUSCULES',title:'Nom Propre',toggle:'Inverser',sponge:'Aléatoire',snake:'snake_case',kebab:'kebab-case',camel:'camelCase',pascal:'PascalCase',noAccents:'Sans accents',noSpaces:'Sans espaces',textColor:'Texte',highlightColor:'Surligneur',underlineColor:'Soulignement',removeColors:'Retirer couleurs',left:'Gauche',center:'Centré',right:'Droite',justify:'Justifié',number:'1. Numérique',letter:'A. Lettres',roman:'I. Romains',bullet:'• Puce',dash:'– Tiret',check:'✓ Coche',arrow:'➜ Flèche',star:'★ Étoile',diamond:'◆ Losange',remove:'Retirer puces'},
 en:{tag:'Give your posts some style ✨',your:'Your text',hint:'Write or paste your post here…',tip:'Select a passage, then tap a tool. With no selection, it applies to all text.',chars:'characters',undo:'Undo',redo:'Redo',emoji:'Emojis',clear:'Clear',styles:'Quick styles',decor:'Decorations',formats:'Case and formats',colors:'Colors and highlighting',paragraphs:'Alignment, paragraphs and lists',preview:'Preview',copy:'Copy',share:'Share',png:'Export PNG',privacy:'🔒 Offline, account-free and tracking-free. Your text stays on this device.',search:'Search emoji…',close:'Close',choose:'Choose a color',empty:'Write some text first.',copied:'Text copied',saved:'Draft saved locally',normal:'Normal',bold:'Bold',italic:'Italic',boldItalic:'Bold italic',serif:'Serif bold',mono:'Monospace',double:'Double-struck',script:'Script',small:'Small caps',full:'Full width',circle:'Circled',underline:'Underline',strike:'Strikethrough',over:'Overline',highlight:'Highlight',spark:'Sparkles',heart:'Hearts',frame:'Framed',sentence:'Sentence',lower:'lowercase',upper:'UPPERCASE',title:'Title Case',toggle:'Toggle',sponge:'SpongeBob',snake:'snake_case',kebab:'kebab-case',camel:'camelCase',pascal:'PascalCase',noAccents:'Remove accents',noSpaces:'Remove spaces',textColor:'Text',highlightColor:'Highlight',underlineColor:'Underline',removeColors:'Remove colors',left:'Left',center:'Centered',right:'Right',justify:'Justified',number:'1. Numbered',letter:'A. Letters',roman:'I. Roman',bullet:'• Bullet',dash:'– Dash',check:'✓ Check',arrow:'➜ Arrow',star:'★ Star',diamond:'◆ Diamond',remove:'Remove bullets'},
 es:{tag:'Da estilo a tus publicaciones ✨',your:'Tu texto',hint:'Escribe o pega tu publicación aquí…',tip:'Selecciona un fragmento y toca una herramienta. Sin selección se aplica a todo.',chars:'caracteres',undo:'Deshacer',redo:'Rehacer',emoji:'Emojis',clear:'Borrar',styles:'Estilos rápidos',decor:'Decoraciones',formats:'Mayúsculas y formatos',colors:'Colores y resaltado',paragraphs:'Alineación, párrafos y listas',preview:'Vista previa',copy:'Copiar',share:'Compartir',png:'Exportar PNG',privacy:'🔒 Sin conexión, cuenta ni rastreo. Tu texto permanece en este dispositivo.',search:'Buscar emoji…',close:'Cerrar',choose:'Elegir un color',empty:'Primero escribe un texto.',copied:'Texto copiado',saved:'Borrador guardado localmente',normal:'Normal',bold:'Negrita',italic:'Cursiva',boldItalic:'Negrita cursiva',serif:'Serif',mono:'Monoespaciado',double:'Doble trazo',script:'Caligrafía',small:'Versalitas',full:'Ancho completo',circle:'Círculos',underline:'Subrayado',strike:'Tachado',over:'Línea superior',highlight:'Resaltador',spark:'Destellos',heart:'Corazones',frame:'Enmarcado',sentence:'Frase',lower:'minúsculas',upper:'MAYÚSCULAS',title:'Tipo Título',toggle:'Invertir',sponge:'Alternado',snake:'snake_case',kebab:'kebab-case',camel:'camelCase',pascal:'PascalCase',noAccents:'Sin acentos',noSpaces:'Sin espacios',textColor:'Texto',highlightColor:'Resaltador',underlineColor:'Subrayado',removeColors:'Quitar colores',left:'Izquierda',center:'Centrado',right:'Derecha',justify:'Justificado',number:'1. Numérica',letter:'A. Letras',roman:'I. Romanos',bullet:'• Viñeta',dash:'– Guion',check:'✓ Marca',arrow:'➜ Flecha',star:'★ Estrella',diamond:'◆ Rombo',remove:'Quitar viñetas'},
 de:{tag:'Verleihe deinen Beiträgen Stil ✨',your:'Dein Text',hint:'Schreibe oder füge deinen Beitrag hier ein…',tip:'Markiere einen Abschnitt und tippe auf ein Werkzeug. Ohne Auswahl gilt es für alles.',chars:'Zeichen',undo:'Rückgängig',redo:'Wiederholen',emoji:'Emojis',clear:'Löschen',styles:'Schnelle Stile',decor:'Dekorationen',formats:'Großschreibung und Formate',colors:'Farben und Markierung',paragraphs:'Ausrichtung, Absätze und Listen',preview:'Vorschau',copy:'Kopieren',share:'Teilen',png:'PNG exportieren',privacy:'🔒 Offline, ohne Konto und Tracking. Dein Text bleibt auf diesem Gerät.',search:'Emoji suchen…',close:'Schließen',choose:'Farbe wählen',empty:'Schreibe zuerst einen Text.',copied:'Text kopiert',saved:'Entwurf lokal gespeichert',normal:'Normal',bold:'Fett',italic:'Kursiv',boldItalic:'Fett kursiv',serif:'Serifenfett',mono:'Monospace',double:'Doppelstrich',script:'Schreibschrift',small:'Kapitälchen',full:'Vollbreite',circle:'Eingekreist',underline:'Unterstrichen',strike:'Durchgestrichen',over:'Überstrichen',highlight:'Markiert',spark:'Funkeln',heart:'Herzen',frame:'Eingerahmt',sentence:'Satz',lower:'klein',upper:'GROSS',title:'Jedes Wort Groß',toggle:'Umkehren',sponge:'Abwechselnd',snake:'snake_case',kebab:'kebab-case',camel:'camelCase',pascal:'PascalCase',noAccents:'Ohne Akzente',noSpaces:'Ohne Leerzeichen',textColor:'Text',highlightColor:'Markierung',underlineColor:'Unterstreichung',removeColors:'Farben entfernen',left:'Links',center:'Zentriert',right:'Rechts',justify:'Blocksatz',number:'1. Nummeriert',letter:'A. Buchstaben',roman:'I. Römisch',bullet:'• Punkt',dash:'– Strich',check:'✓ Häkchen',arrow:'➜ Pfeil',star:'★ Stern',diamond:'◆ Raute',remove:'Liste entfernen'},
 ar:{tag:'أضف لمسة جميلة إلى منشوراتك ✨',your:'نصك',hint:'اكتب أو الصق منشورك هنا…',tip:'حدّد مقطعًا ثم اختر أداة. من دون تحديد تُطبّق على النص كله.',chars:'حرفًا',undo:'تراجع',redo:'إعادة',emoji:'رموز',clear:'مسح',styles:'أنماط سريعة',decor:'زخارف',formats:'حالة الأحرف والتنسيقات',colors:'الألوان والتظليل',paragraphs:'المحاذاة والفقرات والقوائم',preview:'معاينة',copy:'نسخ',share:'مشاركة',png:'تصدير PNG',privacy:'🔒 دون اتصال أو حساب أو تتبع. يبقى النص على هذا الجهاز.',search:'ابحث عن رمز…',close:'إغلاق',choose:'اختر لونًا',empty:'اكتب نصًا أولًا.',copied:'تم نسخ النص',saved:'تم حفظ المسودة محليًا',normal:'عادي',bold:'عريض',italic:'مائل',boldItalic:'عريض مائل',serif:'مزخرف',mono:'أحادي',double:'خط مزدوج',script:'خط يدوي',small:'حروف صغيرة',full:'عرض كامل',circle:'داخل دوائر',underline:'تسطير',strike:'يتوسطه خط',over:'فوقه خط',highlight:'تمييز',spark:'بريق',heart:'قلوب',frame:'إطار',sentence:'حرف أول كبير',lower:'صغيرة',upper:'كبيرة',title:'أول كل كلمة',toggle:'عكس الحالة',sponge:'عشوائي',snake:'snake_case',kebab:'kebab-case',camel:'camelCase',pascal:'PascalCase',noAccents:'دون حركات',noSpaces:'دون مسافات',textColor:'النص',highlightColor:'التظليل',underlineColor:'التسطير',removeColors:'إزالة الألوان',left:'يسار',center:'توسيط',right:'يمين',justify:'ضبط',number:'1. رقمية',letter:'A. حروف',roman:'I. رومانية',bullet:'• نقطة',dash:'– شرطة',check:'✓ صح',arrow:'➜ سهم',star:'★ نجمة',diamond:'◆ معين',remove:'إزالة التعداد'}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lang=localStorage.getItem('textaura-lang')||((navigator.language||'fr').slice(0,2));if(!LANGS.includes(lang))lang='fr';
let doc=loadDoc(), selection={start:0,end:0}, remembered=null, undo=[], redo=[], activeEmoji='smileys';
const editor=$('#editor'),preview=$('#preview'),count=$('#count'),toast=$('#toast'),colorDialog=$('#color-dialog'),emojiDialog=$('#emoji-dialog');
function tr(k){return T[lang]?.[k]??T.fr[k]??k}
function loadDoc(){try{const x=JSON.parse(localStorage.getItem('textaura-doc')||'null');return x&&typeof x.text==='string'&&Array.isArray(x.marks)&&Array.isArray(x.paragraphs)?x:cloneDoc(EMPTY_DOC)}catch{return cloneDoc(EMPTY_DOC)}}
function save(){localStorage.setItem('textaura-doc',JSON.stringify(doc));localStorage.setItem('textaura-lang',lang)}
function notice(s){toast.textContent=s;toast.hidden=false;clearTimeout(notice.t);notice.t=setTimeout(()=>toast.hidden=true,1800)}
function push(){undo.push({doc:cloneDoc(doc),selection:{...selection}});if(undo.length>100)undo.shift();redo=[]}
function restore(x){doc=cloneDoc(x.doc);selection={...x.selection};render();setTimeout(()=>{editor.focus({preventScroll:true});editor.setSelectionRange(selection.start,selection.end)},0)}
function doUndo(){if(!undo.length)return;redo.push({doc:cloneDoc(doc),selection:{...selection}});restore(undo.pop())}
function doRedo(){if(!redo.length)return;undo.push({doc:cloneDoc(doc),selection:{...selection}});restore(redo.pop())}
function currentSel(all=true){const s=normSel(remembered??selection,doc.text.length);return all&&s.start===s.end?{start:0,end:doc.text.length}:s}
function remember(){const a=editor.selectionStart??0,b=editor.selectionEnd??a;selection=normSel({start:a,end:b},doc.text.length);if(selection.start!==selection.end)remembered={...selection}}
function replaceSelected(value,all=true){if(!doc.text&&all){notice(tr('empty'));return}push();const r=currentSel(all),x=replaceRange(doc,r,value);doc=x.doc;selection=x.selection;remembered={...selection};render();focusSelection()}
function focusSelection(){setTimeout(()=>{editor.focus({preventScroll:true});editor.setSelectionRange(selection.start,selection.end)},0)}
function applyUnicode(style){const r=currentSel();replaceSelected(unicodeStyle(doc.text.slice(r.start,r.end),style))}
function applyDecoration(op){const r=currentSel();if(op==='underline'){push();doc=addMark(doc,r,{underline:true});render();return}if(op==='highlight'){openColors('background');return}const v=doc.text.slice(r.start,r.end);replaceSelected(op==='strike'?combine(v,'\u0336'):op==='over'?combine(v,'\u0305'):op==='spark'?`✨ ${v} ✨`:op==='heart'?`💖 ${v} 💖`:`【${v}】`)}
function applyCase(op){const r=currentSel();replaceSelected(caseTransform(doc.text.slice(r.start,r.end),op,lang))}
function applyAlignment(a){if(!doc.text){notice(tr('empty'));return}push();doc=setAlign(doc,currentSel(),a);render()}
function list(op){if(!doc.text){notice(tr('empty'));return}push();const x=applyList(doc,currentSel(),op);doc=x.doc;selection=x.selection;remembered={...selection};render();focusSelection()}
function addColor(kind,color){push();const r=currentSel();doc=addMark(doc,r,kind==='color'?{color}:kind==='background'?{background:color}:{underlineColor:color});render()}
function removeColors(){push();doc=clearMarks(doc,currentSel());render()}
function renderPreview(){preview.replaceChildren();if(!doc.text){preview.textContent='…';preview.classList.add('empty');return}preview.classList.remove('empty');let start=0;const lines=doc.text.split('\n');lines.forEach((line,i)=>{const p=document.createElement('div');p.className='preview-line';p.style.textAlign=alignAt(doc,start);if(alignAt(doc,start)==='justify')p.style.textAlign='justify';const end=start+line.length;segments(doc,start,end).forEach(seg=>{const span=document.createElement('span');span.textContent=seg.text;Object.assign(span.style,seg.style);p.append(span)});if(!line)p.append(document.createElement('br'));preview.append(p);start=end+1})}
function render(){editor.value=doc.text;count.textContent=`${[...doc.text].length} ${tr('chars')}`;renderPreview();save();$('#undo').disabled=!undo.length;$('#redo').disabled=!redo.length}
function setLanguage(v){lang=v;document.documentElement.lang=v;document.documentElement.dir=v==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));editor.placeholder=tr('hint');$('#emoji-search').placeholder=tr('search');$('#language').value=v;renderEmojiTabs();renderEmoji();render();save()}
function makeTools(){const style=[['Abc','normal'],['𝗔𝗯𝗰','bold'],['𝘈𝘣𝘤','italic'],['𝘼𝙗𝙘','boldItalic'],['𝐀𝐛𝐜','serif'],['𝙰𝚋𝚌','mono'],['𝔸𝕓𝕔','double'],['𝒜𝒷𝒸','script'],['ᴀʙᴄ','small'],['Ａｂｃ','full'],['Ⓐⓑⓒ','circle']];toolRow('#style-tools',style,(k)=>applyUnicode(k));toolRow('#decor-tools',[['A̲bc','underline'],['A̶bc','strike'],['A̅bc','over'],['▰ Abc','highlight'],['✨ Abc','spark'],['💖 Abc','heart'],['【Abc】','frame']],applyDecoration);toolRow('#case-tools',[['Abc.','sentence'],['abc','lower'],['ABC','upper'],['Abc Def','title'],['aBC','toggle'],['AbCd','sponge'],['a_b','snake'],['a-b','kebab'],['aBc','camel'],['ABc','pascal'],['é→e','noAccents'],['a b→ab','noSpaces']],applyCase);toolRow('#align-tools',[['↤','left'],['↔','center'],['↦','right'],['☷','justify']],applyAlignment);toolRow('#list-tools',[['1.','number'],['A.','letter'],['I.','roman'],['•','bullet'],['–','dash'],['✓','check'],['➜','arrow'],['★','star'],['◆','diamond'],['✕','remove']],list)}
function toolRow(sel,items,fn){const row=$(sel);items.forEach(([sample,key])=>{const b=document.createElement('button');b.type='button';b.className='tool';b.innerHTML=`<strong></strong><span></span>`;b.querySelector('strong').textContent=sample;b.querySelector('span').textContent=tr(key);b.dataset.key=key;b.addEventListener('pointerdown',e=>e.preventDefault());b.addEventListener('click',()=>fn(key));row.append(b)})}
function openColors(kind){if(!doc.text){notice(tr('empty'));return}remember();colorDialog.dataset.kind=kind;colorDialog.showModal()}
function buildColors(){const colors=['#111827','#6b7280','#dc2626','#f97316','#eab308','#16a34a','#14b8a6','#0284c7','#2563eb','#7c3aed','#c026d3','#db2777','#7c2d12','#0f766e','#4338ca','#be123c','#000000','#ffffff'];const grid=$('#color-grid');colors.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=c;b.ariaLabel=c;b.addEventListener('click',()=>{addColor(colorDialog.dataset.kind,c);colorDialog.close()});grid.append(b)})}
function renderEmojiTabs(){const tabs=$('#emoji-tabs');tabs.replaceChildren();EMOJI_CATEGORIES.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='emoji-tab'+(activeEmoji===c.id?' active':'');b.textContent=`${c.icon} ${c.name[lang]??c.name.fr}`;b.onclick=()=>{activeEmoji=c.id;renderEmojiTabs();renderEmoji()};tabs.append(b)})}
function renderEmoji(){const cat=EMOJI_CATEGORIES.find(c=>c.id===activeEmoji)??EMOJI_CATEGORIES[0],q=$('#emoji-search').value.trim();$('#emoji-category').textContent=cat.name[lang]??cat.name.fr;const grid=$('#emoji-grid');grid.replaceChildren();cat.items.filter(e=>!q||e.includes(q)).forEach(e=>{const b=document.createElement('button');b.type='button';b.className='emoji-cell'+(doc.text.includes(e)?' used':'');b.textContent=e;b.ariaLabel=e;b.onclick=()=>{const s=currentSel(false);push();const x=replaceRange(doc,s,e);doc=x.doc;selection={start:x.selection.end,end:x.selection.end};remembered=null;render();renderEmoji();};grid.append(b)})}
async function copy(){if(!doc.text){notice(tr('empty'));return}await navigator.clipboard.writeText(plainText(doc));notice(tr('copied'))}
async function share(){if(!doc.text){notice(tr('empty'));return}const text=plainText(doc);if(navigator.share)try{await navigator.share({text,title:'TextAura'});return}catch(e){if(e.name==='AbortError')return}await navigator.clipboard.writeText(text);notice(tr('copied'))}
async function exportPng(){if(!doc.text){notice(tr('empty'));return}const scale=Math.min(3,window.devicePixelRatio||2),w=1080,pad=70,max=w-pad*2;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font='36px system-ui, sans-serif';const lines=[];doc.text.split('\n').forEach((para,pi)=>{const words=para.split(/(\s+)/);let line='',start=doc.text.split('\n').slice(0,pi).reduce((n,x)=>n+x.length+1,0);words.forEach(word=>{const test=line+word;if(ctx.measureText(test).width>max&&line){lines.push({text:line.trimEnd(),start});start+=line.length;line=word.trimStart()}else line=test});lines.push({text:line,start})});const lineH=54,h=Math.max(360,pad*2+90+lines.length*lineH);canvas.width=w*scale;canvas.height=h*scale;ctx.scale(scale,scale);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.fillStyle='#7c3aed';ctx.font='bold 34px system-ui';ctx.fillText('TextAura ✦',pad,pad);ctx.font='36px system-ui';lines.forEach((ln,i)=>{const align=alignAt(doc,ln.start),y=pad+80+i*lineH;let x=pad;if(align==='center')x=w/2;if(align==='right')x=w-pad;ctx.textAlign=align==='right'?'right':align==='center'?'center':'left';ctx.fillStyle='#1b1f3b';ctx.fillText(ln.text,x,y,max)});canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TextAura-publication.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
function init(){makeTools();buildColors();setLanguage(lang);editor.addEventListener('select',remember);editor.addEventListener('keyup',remember);editor.addEventListener('pointerup',remember);editor.addEventListener('input',()=>{push();doc=typingUpdate(doc,editor.value);selection={start:editor.selectionStart,end:editor.selectionEnd};remembered=null;render()});$$('button').forEach(b=>{if(!b.closest('dialog'))b.addEventListener('pointerdown',e=>{if(b.id!=='editor')e.preventDefault()})});$('#language').onchange=e=>setLanguage(e.target.value);$('#undo').onclick=doUndo;$('#redo').onclick=doRedo;$('#clear').onclick=()=>{if(!doc.text)return;push();doc=cloneDoc(EMPTY_DOC);selection={start:0,end:0};remembered=null;render()};$('#hide-keyboard').onclick=()=>{remember();editor.blur();notice(tr('saved'))};$('#emoji-open').onclick=()=>{remember();renderEmojiTabs();renderEmoji();emojiDialog.showModal()};$('#emoji-search').oninput=renderEmoji;$('#copy').onclick=copy;$('#share').onclick=share;$('#png').onclick=exportPng;$('#text-color').onclick=()=>openColors('color');$('#highlight-color').onclick=()=>openColors('background');$('#underline-color').onclick=()=>openColors('underline');$('#remove-colors').onclick=removeColors;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());window.addEventListener('beforeunload',save);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));render()}
init();
